name: Development

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  
jobs:
  pre-commit:
    name: Pre Commit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - test
          - fmt
          - clippy
    steps:
      - uses: actions/checkout@v3
      - name: Install Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: 'rustfmt, clippy'
      - name: ${{ matrix.command }}
        uses: actions-rs/cargo@v1
        with:
          command: ${{ matrix.command }}
